version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: fix(deps)
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: terraform
    directories:
      - modules/pihole
    schedule:
      interval: monthly
    commit-message:
      prefix: fix(deps)
    groups:
      terraform-deps:
        patterns:
          - "*"
