name: Pre-commit update

on:
  schedule:
    - cron: 0 6 1 * *
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Auto update
        run: pre-commit autoupdate

      # Create PR if needed
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "ci(pre-commit): updated pre-commit modules on ${{ github.ref_name }}"
          commit-message: "ci(pre-commit): updated pre-commit modules"
          body: Updated pre-commit repos to latest versions
          branch: pre-commit-update/${{ github.ref_name }}
          delete-branch: true
          labels: bot,ci
